// Certificate template definitions
export interface CertificateTemplate {
  id: string;
  name: string;
  description: string;
  // Style tokens used by CertificatePreview
  borderStyle: string;
  bgGradient: string;
  innerBorderColor: string;
  titleFont: string;
  titleColor: string;
  accentColor: string;
  textColor: string;
  footerStyle: string;
  ornamentStyle: 'classic' | 'modern' | 'none' | 'corners' | 'seal';
  // Preview thumbnail gradient for the selector
  previewGradient: string;
  previewAccent: string;
}

export const CERTIFICATE_TEMPLATES: CertificateTemplate[] = [
  {
    id: 'classic',
    name: 'Classic',
    description: 'Traditional navy & gold with double border',
    borderStyle: '8px double hsl(220, 50%, 23%)',
    bgGradient: 'linear-gradient(135deg, #fafafa 0%, #f0f0f0 100%)',
    innerBorderColor: '#c4b896',
    titleFont: 'Georgia, serif',
    titleColor: '#1a365d',
    accentColor: '#b8860b',
    textColor: '#444',
    footerStyle: 'border-t border-[#1a365d]/50',
    ornamentStyle: 'classic',
    previewGradient: 'linear-gradient(135deg, #fafafa, #f0f0f0)',
    previewAccent: '#1a365d',
  },
  {
    id: 'modern-blue',
    name: 'Modern Blue',
    description: 'Clean minimal with blue accents',
    borderStyle: '3px solid #2563eb',
    bgGradient: 'linear-gradient(180deg, #ffffff 0%, #eff6ff 100%)',
    innerBorderColor: '#93c5fd',
    titleFont: "'Helvetica Neue', sans-serif",
    titleColor: '#1e40af',
    accentColor: '#2563eb',
    textColor: '#334155',
    footerStyle: 'border-t border-blue-200',
    ornamentStyle: 'modern',
    previewGradient: 'linear-gradient(180deg, #ffffff, #eff6ff)',
    previewAccent: '#2563eb',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    description: 'Elegant green with gold trim',
    borderStyle: '6px solid #065f46',
    bgGradient: 'linear-gradient(135deg, #fefce8 0%, #ecfdf5 100%)',
    innerBorderColor: '#a3a042',
    titleFont: 'Georgia, serif',
    titleColor: '#065f46',
    accentColor: '#b8860b',
    textColor: '#374151',
    footerStyle: 'border-t border-emerald-300',
    ornamentStyle: 'corners',
    previewGradient: 'linear-gradient(135deg, #fefce8, #ecfdf5)',
    previewAccent: '#065f46',
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    description: 'Regal purple with silver details',
    borderStyle: '6px double #581c87',
    bgGradient: 'linear-gradient(135deg, #faf5ff 0%, #f3e8ff 100%)',
    innerBorderColor: '#a78bfa',
    titleFont: 'Georgia, serif',
    titleColor: '#581c87',
    accentColor: '#7c3aed',
    textColor: '#4b5563',
    footerStyle: 'border-t border-purple-300',
    ornamentStyle: 'classic',
    previewGradient: 'linear-gradient(135deg, #faf5ff, #f3e8ff)',
    previewAccent: '#581c87',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm orange and red tones',
    borderStyle: '4px solid #c2410c',
    bgGradient: 'linear-gradient(135deg, #fffbeb 0%, #fff7ed 50%, #fef2f2 100%)',
    innerBorderColor: '#fb923c',
    titleFont: "'Helvetica Neue', sans-serif",
    titleColor: '#9a3412',
    accentColor: '#ea580c',
    textColor: '#44403c',
    footerStyle: 'border-t border-orange-300',
    ornamentStyle: 'modern',
    previewGradient: 'linear-gradient(135deg, #fffbeb, #fef2f2)',
    previewAccent: '#c2410c',
  },
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Dark elegant with gold accents',
    borderStyle: '4px solid #fbbf24',
    bgGradient: 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)',
    innerBorderColor: '#fbbf24',
    titleFont: 'Georgia, serif',
    titleColor: '#fbbf24',
    accentColor: '#f59e0b',
    textColor: '#cbd5e1',
    footerStyle: 'border-t border-yellow-500/30',
    ornamentStyle: 'seal',
    previewGradient: 'linear-gradient(135deg, #1e293b, #0f172a)',
    previewAccent: '#fbbf24',
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Ultra-clean with thin borders',
    borderStyle: '1px solid #d1d5db',
    bgGradient: 'linear-gradient(180deg, #ffffff 0%, #fafafa 100%)',
    innerBorderColor: '#e5e7eb',
    titleFont: "'Helvetica Neue', sans-serif",
    titleColor: '#111827',
    accentColor: '#6b7280',
    textColor: '#6b7280',
    footerStyle: 'border-t border-gray-200',
    ornamentStyle: 'none',
    previewGradient: 'linear-gradient(180deg, #ffffff, #fafafa)',
    previewAccent: '#111827',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Teal and cyan coastal theme',
    borderStyle: '5px solid #0d9488',
    bgGradient: 'linear-gradient(135deg, #f0fdfa 0%, #ecfeff 100%)',
    innerBorderColor: '#5eead4',
    titleFont: 'Georgia, serif',
    titleColor: '#134e4a',
    accentColor: '#0d9488',
    textColor: '#374151',
    footerStyle: 'border-t border-teal-300',
    ornamentStyle: 'corners',
    previewGradient: 'linear-gradient(135deg, #f0fdfa, #ecfeff)',
    previewAccent: '#0d9488',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    description: 'Soft pink with rose gold accents',
    borderStyle: '4px double #be185d',
    bgGradient: 'linear-gradient(135deg, #fff1f2 0%, #fdf2f8 100%)',
    innerBorderColor: '#f9a8d4',
    titleFont: 'Georgia, serif',
    titleColor: '#9f1239',
    accentColor: '#be185d',
    textColor: '#4b5563',
    footerStyle: 'border-t border-pink-300',
    ornamentStyle: 'classic',
    previewGradient: 'linear-gradient(135deg, #fff1f2, #fdf2f8)',
    previewAccent: '#be185d',
  },
  {
    id: 'corporate',
    name: 'Corporate',
    description: 'Professional slate and blue',
    borderStyle: '3px solid #334155',
    bgGradient: 'linear-gradient(180deg, #ffffff 0%, #f1f5f9 100%)',
    innerBorderColor: '#94a3b8',
    titleFont: "'Helvetica Neue', sans-serif",
    titleColor: '#0f172a',
    accentColor: '#334155',
    textColor: '#475569',
    footerStyle: 'border-t border-slate-300',
    ornamentStyle: 'modern',
    previewGradient: 'linear-gradient(180deg, #ffffff, #f1f5f9)',
    previewAccent: '#334155',
  },
  {
    id: 'vintage',
    name: 'Vintage',
    description: 'Warm parchment with sepia tones',
    borderStyle: '6px double #78350f',
    bgGradient: 'linear-gradient(135deg, #fef3c7 0%, #fde68a40 50%, #fefce8 100%)',
    innerBorderColor: '#92400e',
    titleFont: 'Georgia, serif',
    titleColor: '#78350f',
    accentColor: '#92400e',
    textColor: '#57534e',
    footerStyle: 'border-t border-amber-400/50',
    ornamentStyle: 'seal',
    previewGradient: 'linear-gradient(135deg, #fef3c7, #fefce8)',
    previewAccent: '#78350f',
  },
  {
    id: 'tech',
    name: 'Tech',
    description: 'Modern gradient with neon accents',
    borderStyle: '2px solid #6366f1',
    bgGradient: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)',
    innerBorderColor: '#818cf8',
    titleFont: "'Helvetica Neue', sans-serif",
    titleColor: '#a5b4fc',
    accentColor: '#6366f1',
    textColor: '#c7d2fe',
    footerStyle: 'border-t border-indigo-500/30',
    ornamentStyle: 'none',
    previewGradient: 'linear-gradient(135deg, #0f172a, #1e1b4b)',
    previewAccent: '#818cf8',
  },
];

export function getTemplate(id: string): CertificateTemplate {
  return CERTIFICATE_TEMPLATES.find(t => t.id === id) || CERTIFICATE_TEMPLATES[0];
}
